
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: subscriptions_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 230405
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 230405
      DB_NAME: subscriptions_db
      DB_URL: "postgres://postgres:password@db:5432/subscriptions_db?sslmode=disable"

volumes:
  pgdata:
